In [1]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [3]:
data = np.random.randn(1000) # 服从正太分布

In [ ]:
# cut(x, bins, right=True, labels=None, retbins=False, precision=3,include_lowest=False)

In [12]:
result = pd.cut(data,4)   # data中的（最大值-最小值）/4（分割数） = 分割数
result
pd.value_counts(result)

(-1.267, 0.192]     456
(0.192, 1.651]      375
(-2.733, -1.267]    117
(1.651, 3.11]        52
dtype: int64

In [13]:
result = pd.cut(data,4,precision=2)   # precision 保留有效小数点位数
result   
pd.value_counts(result)

(-1.27, 0.19]     456
(0.19, 1.65]      375
(-2.73, -1.27]    117
(1.65, 3.11]       52
dtype: int64

In [11]:
#qcut(x, q, labels=None, retbins=False, precision=3, duplicates='raise'):
result = pd.qcut(data,4) # 将数据均分成四组，先对数据进行排序，然后再对数据均分为四组
result
pd.value_counts(result)

(0.7, 3.11]                      250
(0.0135, 0.7]                    250
(-0.685, 0.0135]                 250
(-2.7279999999999998, -0.685]    250
dtype: int64

In [15]:
result = pd.qcut(data,[0,0.1,0.5,0.9,1])  # [0,0.1,0.5,0,9,1] 这个数据是0.1 - 0 ；0.5-0.1；0.9-0.5；1-0.9 这个数据当做分位数；还是先排序后分组
pd.value_counts(result)

(0.0135, 1.363]                  400
(-1.339, 0.0135]                 400
(1.363, 3.11]                    100
(-2.7279999999999998, -1.339]    100
dtype: int64

In [16]:
# 如果分位数的差值和小于1的情况下，不会取的全数据 :取完分位数差值所占百分比就不在取得数据
result = pd.qcut(data,[0,0.1,0.3,0.75])
pd.value_counts(result)

(-0.576, 0.7]                    450
(-1.339, -0.576]                 200
(-2.7279999999999998, -1.339]    100
dtype: int64

In [17]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000,4)) 
data

            0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [18]:
# 数据简单的统计信息
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [19]:
col = data[3]
col

0     -0.555730
1      0.281746
2     -1.296221
3      0.886429
4     -0.438570
5     -1.021228
6      0.523772
7     -0.831154
8      0.560145
9      0.332883
10    -0.970736
11    -0.753887
12     0.246674
13    -0.919262
14    -0.660524
15     0.670216
16    -2.304234
17     1.074623
18    -0.503087
19     0.222896
20     0.433610
21     0.850591
22     2.169461
23     0.795253
24     0.152677
25    -0.929006
26     0.980928
27     0.457002
28    -0.402827
29    -1.648985
         ...
970   -1.460094
971    0.132262
972   -1.091849
973   -1.243078
974   -0.521155
975   -0.307670
976    1.381155
977    0.075798
978    0.102469
979    1.120895
980   -0.285176
981    0.053410
982    0.233619
983    0.604880
984   -0.335099
985    1.367213
986   -0.512542
987   -1.050942
988   -0.387002
989    1.642339
990    1.336648
991    0.153988
992   -1.466596
993    1.101972
994    0.604072
995    1.653126
996   -1.502870
997    0.133304
998   -0.303340
999    0.882755
Name: 3, Length: 1000, dtype: float64

NameError: name 'sys' is not defined