In [1]:
import pandas as pd
from pandas import Series,DataFrame

In [2]:
df = pd.read_csv("Student_Alcohol.csv")

In [3]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,services,services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [17]:
### Step 3. 为了便由于分析，请获取到数据集中从列名为school到列名guardian之间的所有数据
# df.loc[:,['school':'guardian']]
df_sub = df.T.loc['school':'guardian'].T
df_sub

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father
12,GP,M,15,U,LE3,T,4,4,health,services,course,father
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother
14,GP,M,15,U,GT3,A,2,2,other,other,home,other
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother
19,GP,M,16,U,LE3,T,4,3,health,other,home,father
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother
21,GP,M,15,U,GT3,T,4,4,health,health,other,father
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father
370,MS,F,19,U,LE3,T,3,2,services,services,home,other
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother
376,MS,F,20,U,GT3,T,4,2,health,other,course,other
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother
382,MS,M,17,U,GT3,T,2,3,other,services,home,father
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother
384,MS,M,18,R,GT3,T,4,2,other,other,home,father
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

In [16]:
# Step 4. 创建一个能实现字符串的首字母大写的lambda匿名函数
# f = lambda x:x[:1].upper()+x[1:].lower()
f = lambda x:x.capitalize()

In [22]:
# Step 5. 将数据列 Mjob 和 Fjob中所有数据实现首字母大写
df[['Mjob','Fjob']].applymap(f)

         Mjob      Fjob
0     At_home   Teacher
1     At_home     Other
2     At_home     Other
3      Health  Services
4       Other     Other
5    Services     Other
6       Other     Other
7       Other   Teacher
8    Services     Other
9       Other     Other
10    Teacher    Health
11   Services     Other
12     Health  Services
13    Teacher     Other
14      Other     Other
15     Health     Other
16   Services  Services
17      Other     Other
18   Services  Services
19     Health     Other
20    Teacher     Other
21     Health    Health
22    Teacher     Other
23      Other     Other
24   Services    Health
25   Services  Services
26      Other     Other
27     Health  Services
28   Services     Other
29    Teacher   Teacher
..        ...       ...
365   At_home     Other
366   Teacher  Services
367     Other  Services
368   At_home  Services
369     Other   Teacher
370  Services  Services
371   At_home  Services
372     Other   At_home
373     Other     Other
374     Other     Other
375     Other     Other
376    Health     Other
377   Teacher  Services
378     Other     Other
379   At_home     Other
380   Teacher   Teacher
381     Other     Other
382     Other  Services
383     Other  Services
384     Other     Other
385   At_home     Other
386   Teacher   At_home
387  Services     Other
388   Teacher  Services
389     Other     Other
390  Services  Services
391  Services  Services
392     Other     Other
393  Services     Other
394     Other   At_home

[395 rows x 2 columns]

In [23]:
#Step 6. 经过第6步之后，为什么原来的dataframe数据中Mjob和Fjob列的数据仍然是小写的？简单说明原因，
# 并修改原始dataframe中的数据使得Mjob和Fjob列变为首字母大写
# 因为修改的是原始的视图复本，没有对原始数据进行修改
df[['Mjob','Fjob']] = df[['Mjob','Fjob']].applymap(f)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,Services,Other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,Other,Other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,Other,Teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,Services,Other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,Other,Other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,Teacher,Health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,Services,Other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,Health,Services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,Other,Other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,Health,Other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,Services,Services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,Other,Other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,Services,Services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,Health,Other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,Health,Health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,Teacher,Other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,Other,Other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,Services,Health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,Services,Services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,Other,Other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,Health,Services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,Services,Other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,Teacher,Teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,At_home,Other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,Teacher,Services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,Other,Services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,At_home,Services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,Other,Teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,Services,Services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,At_home,Services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,Other,At_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,Other,Other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,Other,Other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,Other,Other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,Health,Other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,Teacher,Services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,Other,Other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,At_home,Other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,Teacher,Teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,Other,Other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,Other,Services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,Other,Services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,Other,Other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,At_home,Other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,Teacher,At_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,Services,Other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,Teacher,Services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,Other,Other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,3,2,3,3,3,5,5,8,9,9

In [24]:
# Step 7.创建一个名为majority函数，并根据age列数据返回一个布尔值添加到新的数据列，
# 列名为 legal_drinker (根据年龄这一列数据，大于17岁为合法饮酒)4
def majority(dataFrame):
    legal_drinker = dataFrame['age']>17
    dataFrame['legal_drinker'] = legal_drinker

In [25]:
majority(df)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False
5,GP,M,16,U,LE3,T,4,3,Services,Other,...,4,2,1,2,5,10,15,15,15,False
6,GP,M,16,U,LE3,T,2,2,Other,Other,...,4,4,1,1,3,0,12,12,11,False
7,GP,F,17,U,GT3,A,4,4,Other,Teacher,...,1,4,1,1,1,6,6,5,6,False
8,GP,M,15,U,LE3,A,3,2,Services,Other,...,2,2,1,1,1,0,16,18,19,False
9,GP,M,15,U,GT3,T,3,4,Other,Other,...,5,1,1,1,5,0,14,15,15,False
10,GP,F,15,U,GT3,T,4,4,Teacher,Health,...,3,3,1,2,2,0,10,8,9,False
11,GP,F,15,U,GT3,T,2,1,Services,Other,...,2,2,1,1,4,4,10,12,12,False
12,GP,M,15,U,LE3,T,4,4,Health,Services,...,3,3,1,3,5,2,14,14,14,False
13,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,4,3,1,2,3,2,10,10,11,False
14,GP,M,15,U,GT3,A,2,2,Other,Other,...,5,2,1,1,3,0,14,16,16,False
15,GP,F,16,U,GT3,T,4,4,Health,Other,...,4,4,1,2,2,4,14,14,14,False
16,GP,F,16,U,GT3,T,4,4,Services,Services,...,2,3,1,2,2,6,13,14,14,False
17,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,1,4,4,8,10,10,False
18,GP,M,17,U,GT3,T,3,2,Services,Services,...,5,5,2,4,5,16,6,5,5,False
19,GP,M,16,U,LE3,T,4,3,Health,Other,...,1,3,1,3,5,4,8,10,10,False
20,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,4,1,1,1,1,0,13,14,15,False
21,GP,M,15,U,GT3,T,4,4,Health,Health,...,4,2,1,1,5,0,12,15,15,False
22,GP,M,16,U,LE3,T,4,2,Teacher,Other,...,5,1,1,3,5,2,15,15,16,False
23,GP,M,16,U,LE3,T,2,2,Other,Other,...,4,4,2,4,5,0,13,13,12,False
24,GP,F,15,R,GT3,T,2,4,Services,Health,...,3,2,1,1,5,2,10,9,8,False
25,GP,F,16,U,GT3,T,2,2,Services,Services,...,2,2,1,3,5,14,6,9,8,False
26,GP,M,15,U,GT3,T,2,2,Other,Other,...,2,2,1,2,5,2,12,12,11,False
27,GP,M,15,U,GT3,T,4,2,Health,Services,...,2,4,2,4,1,4,15,16,15,False
28,GP,M,16,U,LE3,A,3,4,Services,Other,...,3,3,1,1,5,4,11,11,11,False
29,GP,M,16,U,GT3,T,4,4,Teacher,Teacher,...,4,5,5,5,5,16,10,12,11,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,At_home,Other,...,3,4,2,4,3,4,10,10,10,True
366,MS,M,18,U,LE3,T,4,4,Teacher,Services,...,2,2,2,2,5,0,13,13,13,True
367,MS,F,17,R,GT3,T,1,1,Other,Services,...,2,1,1,2,1,0,7,6,0,False
368,MS,F,18,U,GT3,T,2,3,At_home,Services,...,2,3,1,2,4,0,11,10,10,True
369,MS,F,18,R,GT3,T,4,4,Other,Teacher,...,2,2,4,2,5,10,14,12,11,True
370,MS,F,19,U,LE3,T,3,2,Services,Services,...,2,2,1,1,3,4,7,7,9,True
371,MS,M,18,R,LE3,T,1,2,At_home,Services,...,3,3,2,3,3,3,14,12,12,True
372,MS,F,17,U,GT3,T,2,2,Other,At_home,...,4,3,1,1,3,8,13,11,11,False
373,MS,F,17,R,GT3,T,1,2,Other,Other,...,5,5,1,3,1,14,6,5,5,False
374,MS,F,18,R,LE3,T,4,4,Other,Other,...,4,4,1,1,1,0,19,18,19,True
375,MS,F,18,R,GT3,T,1,1,Other,Other,...,3,2,1,2,4,2,8,8,10,True
376,MS,F,20,U,GT3,T,4,2,Health,Other,...,4,3,1,1,3,4,15,14,15,True
377,MS,F,18,R,LE3,T,4,4,Teacher,Services,...,4,3,3,4,2,4,8,9,10,True
378,MS,F,18,U,GT3,T,3,3,Other,Other,...,1,3,1,2,1,0,15,15,15,True
379,MS,F,17,R,GT3,T,3,1,At_home,Other,...,5,4,2,3,1,17,10,10,10,False
380,MS,M,18,U,GT3,T,4,4,Teacher,Teacher,...,2,4,1,4,2,4,15,14,14,True
381,MS,M,18,R,GT3,T,2,1,Other,Other,...,4,3,1,3,5,5,7,6,7,True
382,MS,M,17,U,GT3,T,2,3,Other,Services,...,4,3,1,1,3,2,11,11,10,False
383,MS,M,19,R,GT3,T,1,1,Other,Services,...,3,2,1,3,5,0,6,5,0,True
384,MS,M,18,R,GT3,T,4,2,Other,Other,...,4,3,4,3,3,14,6,5,5,True
385,MS,F,18,R,GT3,T,2,2,At_home,Other,...,3,3,1,3,4,2,10,9,10,True
386,MS,F,18,R,GT3,T,4,4,Teacher,At_home,...,4,3,2,2,5,7,6,5,6,True
387,MS,F,19,R,GT3,T,2,3,Services,Other,...,4,2,1,2,5,0,7,5,0,True
388,MS,F,18,U,LE3,T,3,1,Teacher,Services,...,3,4,1,1,1,0,7,9,8,True
389,MS,F,18,U,GT3,T,1,1,Other,Other,...,1,1,1,1,5,0,6,5,0,True
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,4,4,5,4,11,9,9,9,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,4,5,3,4,2,3,14,16,16,False
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,3,3,3,3,3,10,8,7,True
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,1,3,4,5,0,11,12,10,True
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,2,3,3,3,5,5,8,9,9,True